name: CI

on:
  push:
    branches: ["master"]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        rust: [beta, stable, 1.38.0]
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - rust: nightly
            os: ubuntu-latest
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - run: cargo fmt -- --check
      - run: cargo test
      - run: |
             if [ "${{ matrix.rust }}" = "nightly" ]; then
               cargo bench
             else
               true
             fi
